name:                Fib
version:             0.1.0.0
github:              "rolandtritsch/elixir-ldn-2019"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2019 Roland Tritsch"

description:         Please see the README on GitHub at <https://github.com/rolandtritsch/elixir-ldn-2019#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fib

tests:
  fib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - Fib
